### ISSUE TITLE
Game doesn't work in full screen

### ISSUE THREAD

**Issue by Coockie** [1oom-fork/1oom#2]
If i run game first time when it run at window mode and then works fine. If i enable full screen mode in game settings and then click "Game" then aplication imediately closes and settings doesn't saves.
My system is Windows 11 "Microsoft Windows [Version 10.0.22000.978]" I have two monitor 1920x1200 - Primary and 1920x1080 - secondary it's disabled when i test the game. CPU - AMD Ryzen 5 3600 and GPU NVidia GTX 1066
[1oom_log.txt](https://github.com/1oom-fork/1oom/files/9665365/1oom_log.txt)

**Comment by 1oom-fork** [comment]
Please provide the latest version of the game that works fine for you

**Comment by Coockie** [comment]
I found out what caused this trouble: it's MSI AfterBurner 4.6.4 Overlay, if i exit this application then full screen working.
