### ISSUE TITLE
Suggestion: Create free art pack?

### ISSUE THREAD

**Issue by sheepo99** [1oom-fork/1oom#37]
Since 1oom has been included the Debian repositories, I wanted to float the idea to create a free art pack (sort of like OpenTTD does), to effectively make the project 100% free and able to run on its own. We could try either sourcing pixel art from the community or alternatively we could do a crowdfunding drive to contract a couple of good pixel artists to produce quality artwork. This would mean 1oom could turn into a more encompassing project, not only providing a better way to run the original MoO, but also gain a life of its own and be a truly free 4x game available for all audiences free of charge.

Crowdfunding could be done via Patreon, Indiegogo, Liberapy of Kofi, and we could even discuss what sort of artwork could fit the game best.

**Comment by 1oom-fork** [comment]
Unfortunately 1oom is far from MOO1. It will take a lot of time to correct all the typos. So it's too early to say "to run the original MOO". Debian developers don't seem to care about the quality of the project.

**Comment by sheepo99** [comment]
I see, I was under the impression this fork had addressed most of the issues with Kilgore's previous builds. I'm keeping an eye on this repo. Thank you for the reply.
