### ISSUE TITLE
slider_stop_terraform_fix setting causes error in 1oom_pbxmake

### ISSUE THREAD

**Issue by sytnik-aa** [1oom-fork/1oom#41]
Hi!, I have an issue with 1.8.0 and 1.8.1 releases. 

When I take an unmodified version of the https://github.com/1oom-fork/1oom/blob/master/doc/pbxin_fixbugs.txt and try to convert it to a PBX format using 1oom_pbxmake pbxin_fixbugs.txt pbxin_fixbugs.pbx I get the error: 

error: error: too long item id string 'slider_stop_terraform_fix' (25 > 24) at 2026

I use x64 releases. 

Thank you!

**Comment by 1oom-fork** [comment]
This file is probably corrupted. If necessary, I can check it. But you can do it yourself if you want.

**Comment by 1oom-fork** [comment]
OK. Looks like it's obvious what's wrong

**Comment by 1oom-fork** [comment]
Changed slider_stop_terraform_fix to slider_stop_tform_fix
https://github.com/1oom-fork/1oom/commit/60edcf77b0ddeb62b35a25d330a0fc705174ebe8
https://github.com/1oom-fork/1oom/releases/download/f1.8.1/1oom-fork-v1.8.1-x64-1.zip

**Comment by 1oom-fork** [comment]
Feel free to report other bugs. I haven't tested pbx

**Comment by sytnik-aa** [comment]
Thank you very much, it's working! 

> Feel free to report other bugs.

Will do!
