### ISSUE TITLE
Feature Request: Display Colonized Planet's Mineral Status on Planet's Overview Screen

### ISSUE THREAD

**Issue by sytnik-aa** [1oom-fork/1oom#43]
A small quality of life request. I think it would be nice if the planet overview screen (the one with the star in the top right corner) showed the planet's "mineral" status (rich, poor, artifacts, etc.). It's already displayed in the bottom left corner for the uncolonized planets, but not for the colonized ones. Thanks!

**Comment by 1oom-fork** [comment]
The problem comes when we get a Fertile/Ultra Poor planet. We need to come up with a shortcut. I'm not good at abbreviations in English.

**Comment by 1oom-fork** [comment]
We need to study in more detail how this works. In many cases the status is indicated

**Comment by 1oom-fork** [comment]
From ui_starmap_draw_planetinfo_do:
                if (p->special == PLANET_SPECIAL_NORMAL) {
                    str = game_str_tbl_sm_pgrowth[p->growth];
                } else {
                    str = game_str_tbl_sm_pspecial[p->special];
                }
As far as I know the mineral status is displayed. Correct me if I understood something wrong or attach a picture

**Comment by sytnik-aa** [comment]
Sorry, some screenshots: 
Uncolonized planet: 
<img width="722" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/c91498ab-69d3-4f2d-ace9-e141d17b3724">
Colonized planet (it's a different planet, but it's poor): 
<img width="723" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/5ba37f08-7be7-4071-a5cd-b2fcd55fafe5">
<img width="206" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/e21eede1-a3b6-4804-9dd2-2bd2ca5bfe89">

**Comment by 1oom-fork** [comment]
Oh, well, if that's the case, it's easy to fix, I'll take a look

**Comment by sytnik-aa** [comment]
I've also noticed this little thing: 

<img width="724" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/0d31dbb2-2fac-4a46-a695-60755d6ec8dc">

The part of the text about mineral status doesn't have an outline. The descriptions have and the "Hostile" part too.

**Comment by 1oom-fork** [comment]
This little thing is a typo. Fixed 714cc46ab5d173040e7d3588d1d9ece3991d1b9e.
Thanks for the valuable find

**Comment by 1oom-fork** [comment]
Returning to the main topic, to add inscriptions, we must take into account the appearance of an inhabited planet with 300 population, 2700 factories and pollution, 100 if I'm not mistaken. I'll try to craft a similar planet later. I hope there's still some free space there. In addition, we will need to check how random events are displayed.

**Comment by 1oom-fork** [comment]
![Screenshot_20240323_123402](https://github.com/1oom-fork/1oom/assets/23404794/1c4210ab-b941-4efc-b072-e6a23460a770)

**Comment by 1oom-fork** [comment]
![Screenshot_20240323_124044](https://github.com/1oom-fork/1oom/assets/23404794/d16bff5d-37df-4fab-b351-bb2a27054e4a)
I'm not sure that's all that can be drawn there

**Comment by sytnik-aa** [comment]
Yeah, I think that's why the devs didn't do it in the first place. I'll think about possible solutions, thank you!

**Comment by 1oom-fork** [comment]
I don't think it's important enough to waste energy on it.

**Comment by 1oom-fork** [comment]
Okay, I have good news. The bottom right frame is a hard-coded rectangle that can be resized, so the screen is quite flexible.

**Comment by 1oom-fork** [comment]
There is another idea. Once I implement the ability to render and overlay multiple textures with different palettes, it will be possible to combine screens, such as planet controls with this picture. Now the main difficulty for me is to plan everything so that I don’t regret it later.

**Comment by sytnik-aa** [comment]
Thank you! The issue is minor indeed, but I think it would be great to finally solve it after 30 years :) It is cool if the green box in the bottom right corner can be used for that. I'll think more about it and try to visialize any ideas I have. Thanks!

**Comment by 1oom-fork** [comment]
I think it would be quite ugly in the corners, especially if it blocks the sun. You can make several tabs at the bottom right. A lot of information will fit there if you come up with an abbreviated text

**Comment by 1oom-fork** [comment]
I will need pictures of vertical arrows to scroll through lines in the lower right corner. Either rotated arrows from one of the fonts, or something from ready-made graphics in LBX

**Comment by 1oom-fork** [comment]
I cleaned up the topic a little because I have 2 ready-made solutions. Either scrolling the green frame, then I need graphic arrows from fonts or pictures of arrows, or even simpler, you can simply replace the image on the left with the necessary information by clicking the mouse, as in the weapon selection window. Nothing prevents us from making 2 options at once. I expect everything to fit

**Comment by 1oom-fork** [comment]
Clicking on the screen at any point switches the mode of displaying information for inhabited planets
84ac5c0960c2ffa060bad023a775010cf65155f1
