### ISSUE TITLE
Feature Request: Make fleets clickable on the Galaxy Map and/or make the entire map clickable

### ISSUE THREAD

**Issue by sytnik-aa** [1oom-fork/1oom#49]
Now on the Galaxy Map you can only click on stars. 

I think it would be cool if fleets were also clickable (I know it can be messy becuase sometimes there are just a lot of fleets on the map, but I ask to consider this option anyway). 

<img width="721" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/1991a227-2fa2-4cb6-80cc-81661cc455e2">

Also, why can't I just click anywhere on the map and focus on this particular piece of the galaxy (that's how minimaps usually work).  

Thanks!

**Comment by 1oom-fork** [comment]
Ignatius has many changes regarding this interface element. Of course, they are subject to evaluation and it may be reasonable to add some of them. But this problem conflicts with the implementation of scaling. My plans are to write a simplified version of scaling that allows hardware acceleration. After this, it will be possible to introduce a single representation of coordinate transformation and use it.

**Comment by 1oom-fork** [comment]
I would also like to clarify that adding new functions is secondary for me; the priority is cleaning the existing code to simplify comparison with the original
