### ISSUE TITLE
Either disable the copy protection or mention it is active

### ISSUE THREAD

**Issue by alienfs** [1oom-fork/1oom#55]
I just tried the game for the first time. I was doing really well because the galaxy generation was favorable. At some point I got the copy protection question and as per usual I simply clicked somewhere. Oddly, I got a second question and then a third and BOOM. Game over.

Seriously, having the copy protection active is not really enjoyable. I don't want to ALT+TAB out of the game and browse some .pdf manual. I paid for the game, alright. Multiple times: Boxed copy, Gamestop, Steam, Gog, Master of Orion: Collector's Edition).

At the very least mention in the README that the copy protection is not disabled. It killed my first experience.

**Comment by 1oom-fork** [comment]
Thanks for your feedback.
You help clarify the situation, which greatly contributes to the development of the project.
Regarding the documentation: it became obvious to me that it is quite difficult to quickly find a way out of this situation. In the advanced settings you can disable copy protection, and also restore your game if you haven’t started a new one yet. I am working on the optimal solution to the problem and will be glad to further cooperation on this issue.

**Comment by 1oom-fork** [comment]
And also, I would like to ask you not to be offended, since it is not my task to entertain you. My task is to restore vanilla behavior.

**Comment by alienfs** [comment]
Actually before I started I did browse all menus and was positively surprised at the additions that you implemented.
I guess I skipped over "skip copy protection" in the menu "interface", although even then I would never have guessed the actual pop-up would result in an end game sequence when just clicking something. (Non of the other versions/clones on the Internet have that behavior.)

Feedback: from a user perspective "disable copy protection" makes a bit more sense, while I understand technically you "skip" it. Having it enabled by default would prevent someone else from running into the same surprise as I did.

I wasn't able to restore my game instance via the in-game menu, however after copying the save file "1oom_save8.bin" to "1oom_save1.bin" I was able to load it via the in-game menu. I was surprised to learn you save the first turn as "1oom_save9.bin". That gives interesting options.

**Comment by 1oom-fork** [comment]
I've been studying different versions of MOO v1.3. In one of them, the conditional jump that triggers the end game sequence is simply cut out. In IDA5 it looks like code that doesn't start anywhere. I was a little puzzled when I saw this, but came to the conclusion that it was a hack. Given the opportunity, I may try to write a patch that will make some versions of vanilla moo 1.3 behave the same as 1oom or completely cut this feature from the original.

**Comment by 1oom-fork** [comment]
Options -> Add-ons -> Load Options Extra On
This allows you to load save 7,8,9.
This feature was added by Kilgore T.M. Replicant before v1.0 release

**Comment by 1oom-fork** [comment]
Regarding interesting options: I played one very interesting map in 1oom and decided to play it in vanilla moo v1.3. To do this, I converted save 9 to the original format using saveconv. You can see it here https://youtu.be/oP569Cut2wE, I think the map is simply amazing

**Comment by 1oom-fork** [comment]
This issue is more of a general documentation issue, so I'm closing it as a partial case.
