### ISSUE TITLE
Small Descrepancies on Planet Screen in Ships and Transports Interfaces

### ISSUE THREAD

**Issue by sytnik-aa** [1oom-fork/1oom#56]
There are several minor interface inconsistencies in the planet screen related to ships and transports. 

1. The error messages in the Transports dialog have different styles: 

Green text without outline
<img width="200" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/ac443f04-520f-45af-b368-186ae033c406">

Green text with outline
<img width="202" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/2b03f1bd-d624-471d-9afd-8811d3d30061">

Black text
<img width="201" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/c1fd52e6-6393-4bcf-9180-e2ac9ab673f2">

Black seems the most appropriate for me in all cases. 

2. Accept button in the Ship Relocation dialog should be disabled unless a valid target is chosen: 

<img width="202" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/4612c3d1-121a-49e6-8f60-4edf3caccff2">

Compare with the similar button on the Transports screen. 

<img width="202" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/f26136a8-3466-47a9-887a-09614d7eb765">

3. Cancel and Accept buttons in the Ships dialog have the same functionality

<img width="209" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/5c190ad9-80b0-48b2-900c-ce980504067b">

No matter which button you click, the selected ship will be chosen for production anyway. I think that the Cancel button should leave the ship that was selected before. 

Also, clicking Cancel button should produce a different sound, but on this screen the sound for Cancel and Accept buttons is the same. 

4. Ship production carousel can be rotated only to the right

<img width="123" alt="image" src="https://github.com/1oom-fork/1oom/assets/40230135/e01ae380-9577-4bf4-a562-0021ffc06100">

There are only 6 items on it, so it's not a big deal, but I prefer to have an option to rotate it to the left too. Can we use the right mouse button click for that? Looks natural for me. 

Thanks!

**Comment by 1oom-fork** [comment]
Thanks for your feedback. It's all in one pile, so I can't comment right away. I will answer when I have enough free time.

**Comment by 1oom-fork** [comment]
Hello. I'm posting in this thread so you can be notified. I have implemented your suggestion regarding the map. It will be available in version 1.10. The corresponding issue is closed as completed
