### ISSUE TITLE
Web port

### ISSUE THREAD

**Issue by midzer** [1oom-fork/1oom#75]
Hi,

I've ported the game in the browser via Emscripten toolchain.

Relevant changes at https://github.com/midzer/1oom/tree/emscripten

Have a nice week
midzer

**Comment by 1oom-fork** [comment]
It would be great if there was minimal documentation

**Comment by 1oom-fork** [comment]
I have many reasons not to add this. If you are interested, you can find answers to some of my questions about this build. At this point I'm not sure if adding this to the main branch would be a good idea.

**Comment by 1oom-fork** [comment]
I have no plans to add this branch in its current form, nor will I be adding statically linked LBX executables, since the latter is against the fair use doctrine. However, I am also not going to close this issue. If you post clearer instructions, I'll take them into consideration.
