### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by OldGamer87** [1oom-fork/1oom#77]
Why not added simple battle grid in space combat? This allow better  orientation in space. 
I play MoO and other strategy games early '90, (atari,commodeore, amiga,). MoO is my best strategy gamer ever.
Always i miss battle grid in combat. Can be very simple, players can enabled/disabled this in menu. Why no one mentioned it??
Players nod need this? I know battle grid size, 8x10, but minor patch update this will be excellent! Thnx for all team for hard working for free on this excellent project nad many hours yours work makes our happy :) 
I joined to Github by add this post. MoO occupies special place in my heart.
Best regards all MoO team. You are my hero.
Sry for my english

**Comment by 1oom-fork** [comment]
Thank you for your kind words. I should clarify that 1oom is an unofficial project and has no relation to the creators of Master of Orion 1993. Your proposal regarding the battlefield is easy to implement, I will do it. I will also be happy to consider any other suggestions you may have.

**Comment by 1oom-fork** [comment]
https://github.com/1oom-fork/1oom/releases/tag/v1.10.1
Turn on UI Extra, press g to switch grid. Enjoy

**Comment by OldGamer87** [comment]
Kull Wahad!! Thank You so much :D

**Comment by 1oom-fork** [comment]
If you really want to thank me, give the project a star. This helps with promotion.
