### ISSUE TITLE
Planets screen: 'space dock" column not interactive 

### ISSUE THREAD

**Issue by mrwonderfulone** [1oom-fork/1oom#84]
Previous versions allowed you to click on the name of the ship in the space dock column to change it to the next ship type.  Version 1.10.2 both left and right clicking this closes the planets screen.

**Comment by 1oom-fork** [comment]
Initially, this window was not intended to be interactive. Clicking on a line selects a planet and you use the main interface to change the ship. That's how it was intended. This feature worsens the design rather than improves it.
