### ISSUE TITLE
New keyboard shortcuts list

### ISSUE THREAD

**Issue by GitHubinatrix** [1oom-fork/1oom#90]
What file holds the list of new keyboard shortcuts?

By accident I have discovered ``ALT+O`` for toggling info about systems in the main / galaxy screen and read in description of https://github.com/1oom-fork/1oom/releases/tag/v1.10.3 that ``G`` shows grid in the battle screen

**Comment by 1oom-fork** [comment]
https://github.com/1oom-fork/1oom/blob/master/doc/usage_classic.txt and MOO1 manual.

**Comment by 1oom-fork** [comment]
It might be a good idea to make a separate list, but it hasn't been a priority until now, I don't know how necessary it is

**Comment by 1oom-fork** [comment]
I plan to combine the new hotkeys into one function, then you will be able to see them all in its description.
