### ISSUE TITLE
Soundfont question

### ISSUE THREAD

**Issue by ManuLinares** [1oom-fork/1oom#96]
I'm using FluidR3_GM.sf2 for a soundfount. I know this is subjective but, What are the best recommended soundfonts for this game?

**Comment by oblivioncth** [comment]
https://gitlab.com/psi29a/opl3-soundfont

Is great for how I'm used to the game sounding.

**Comment by 1oom-fork** [comment]
I like the default Debian soundfont. I also like this one (https://aur.archlinux.org/packages/soundfont-fatboy)

**Comment by 1oom-fork** [comment]
It looks like the soundfont above is a mirror of https://github.com/Mindwerks/opl3-soundfont
The sound seemed rough to me, but quite natural
