### ISSUE TITLE
Renamed: Misunderstanding

### ISSUE THREAD

**Issue by 0Fedaykin0** [1oom-fork/1oom#97]
Edit: Irrelevant

**Comment by 1oom-fork** [comment]
This feature was removed intentionally for multiple reasons.
Speaking in the abstract, I try to remove everything that currently does not fit into the original idea of ​​​​the authors of Master of Orion 1993

**Comment by 1oom-fork** [comment]
By the way, you just gave me a brilliant idea. Thank you.

**Comment by 1oom-fork** [comment]
I would also like to point out that since there is only one original, created in 1993, and the 2018 version contains many gross errors and careless changes, it would be inaccurate to call the 2018 1oom the original. Let's not mislead people.

**Comment by 0Fedaykin0** [comment]
I see, and thanks for the quick reply.

If I may, I'd like to argue that, similar to the auto-retreat and auto-resolve combat options added by Kilgore, this feature would simply automate actions that players can already do manually.
For example, even without these features, you can press auto-combat to watch animations or manage planets in the same way a governor would.
These features are primarily about convenience, saving time on tasks that can often be tedious to manage manually.
If I remember correctly, one of the common criticisms of Master of Orion was that managing a large number of planets in the late game felt cumbersome.

From my experience, I imagine many players have, at least once, forgotten to stop building missile bases on a planet, only to later discover they had 500+ of them consuming a huge portion of their production.

That being said, I understand that this is your repository/fork, and you might not want such a feature here.

PS: Is there a project forum, or is all communication handled via GitHub issues and general discussions?

**Comment by 1oom-fork** [comment]
All your comments about governor are predictable and a close to optimal decision has long been made based on the goals of the project. It’s most convenient for me to communicate here, since I have certain rights to filter garbage.
The decisions I make are necessary to achieve the project's goals. Criticism of my decisions regarding code that is not related to the original does not bother me at all.

**Comment by 1oom-fork** [comment]
By the way, regarding the original 1oom. Version 0.1, although not functional, is much closer to the original compared to 1.0. I'm currently relocating the project to this version. This is the biggest thing I've done with the project.

**Comment by 0Fedaykin0** [comment]
Ah now I've found out that it was indeed removed in version 1.10.0, sorry for bothering you with it then.
Also is the goal of this project to recreate a pure vanilla experience as closely as possible, with an option to toggle bugfixes?
The small paragraph at the beginning of the README could provide more information about it.

**Comment by 1oom-fork** [comment]
If you think that I am misleading you, it will be very useful for me to know my mistake.

**Comment by 1oom-fork** [comment]
Might be worth adding a table of contents

**Comment by 0Fedaykin0** [comment]
Well, I tried to read most of the issues here and commit messages to try to understand the scope/goal of this project, I also read the PHILOSOPHY file, which is pretty much the same as Kilgore's.

Not sure what you mean by misleading here. It could just be a problem on my end, "but I find it a bit difficult to understand which changes would be welcome and which are out of the scope or against the goals.

Or better yet, what are the current goals as for example in issue #33 you said [this](https://github.com/1oom-fork/1oom/issues/33#issuecomment-1979496233), explaining there the current goals there.

I’m the kind of person who tries to read as much as possible so I don't have to bother other people with potentially pointless/bad suggestions. Somehow I still failed.

**Comment by 1oom-fork** [comment]
Everything is simple here. You are either useful to the project or you are not. The less you adapt, the faster things will become clearer.

**Comment by 1oom-fork** [comment]
Besides, you are now teaching me how to communicate with people like you. You won’t get any gratitude for this, but at least I won’t think that I wasted my time on you.

**Comment by 0Fedaykin0** [comment]
I do agree that things are simple here, perhaps just adding what the "original idea of ​​​​the authors of Master of Orion 1993" exactly is would be enough? As currently is sounds bit open to interpretation

**Comment by 1oom-fork** [comment]
I'm deliberately not specifying. You have presented an interesting idea.

**Comment by 0Fedaykin0** [comment]
Feel free to close this issue then and thank you

**Comment by 1oom-fork** [comment]
Alas, there is nothing to be grateful for

**Comment by 1oom-fork** [comment]
The fact is that the source binary code reflects the idea of ​​the authors, but the idea of ​​the authors is not known to us, but the source code actually exists. Therefore, the wording that exists at the moment is more appropriate.

**Comment by 1oom-fork** [comment]
In any case, you have made a significant contribution to my understanding of documentation problems.

**Comment by 0Fedaykin0** [comment]
Glad to hear at least something came out of it.

**Comment by 1oom-fork** [comment]
And one more thing. Now I'm only interested in checking the original binary code with the 1oom code. If you could help with this, I think you would have already offered it to me.

**Comment by 1oom-fork** [comment]
You can check out the first 150+ commits in the 1.12-staging branch. That's what I'm doing right now, sorting through the tested fixes.

**Comment by 0Fedaykin0** [comment]
I do have some basic understanding of x86 disassembly but yes it would rather be a difficult task for me, plus I've never reversed engineerd a 16bit binary tho. 
And yes thanks I'll check out those commits as you said.

**Comment by 1oom-fork** [comment]
The author has a database for IDA5 with documented assembly code

**Comment by 0Fedaykin0** [comment]
That would make things way easier if thats the case

**Comment by 1oom-fork** [comment]
It will be much easier if I finish my translator for the code from IDA5. Now it only makes indents.

**Comment by 1oom-fork** [comment]
Well, he can also twist formulas in such a barbaric way. This is not enough when it comes to branches:
proc get_research_d0_b0(word field_p1, word tech)
var_2 = ((lword(((_0_field_p1-1)*50))+_1_tech)-1);
dx = uword((((lword(((_0_field_p1-1)*50))+_1_tech)-1)*6));
bx = (&research_lbx_0_addr+lword((((lword(((_0_field_p1-1)*50))+_1_tech)-1)*6)));
al = _2_*((&research_lbx_0_addr+lword((((lword(((_0_field_p1-1)*50))+_1_tech)-1)*6))));
ax = _2_*((&research_lbx_0_addr+lword((((lword(((_0_field_p1-1)*50))+_1_tech)-1)*6))));
retf

**Comment by 1oom-fork** [comment]
And yes, I will change these commits, so it’s better to look at them after the release of 1.12
