### ISSUE TITLE
Disable mouse lock in windowed mode

### ISSUE THREAD

**Issue by ponycalypsenow** [1oom-fork/1oom#98]
Sorry, if somehow it's already addressed, but i couldn't find the option - it would be cool, if in the windowed mode the app didn't grab the mouse focus, this way you could play windowed, while doing other thing on your computer, without the need of alt - tabbing all the time.

Great work with the project, much appreciated!

**Comment by 1oom-fork** [comment]
To help, answer the question which sections of the documentation you have already read

**Comment by ponycalypsenow** [comment]
Ah, middle-click releasing the focus is one of the first things mentioned in the usage_classic.txt. My mistake, just being used to the way Dosbox did that.

I think the current solution works even better, since there are no problems with edge scrolling, so there's little reason to change that (other than some people being more familiar with the usage pattern). Thanks for the swift response!
